# Vector Norms

Vector norm is just a fancy name for the calculation of the length or magnitude of a vector. The length of the vector is referred to as the vector norm or the vector’s magnitude. It is calculated using some measure that summarizes the distance of the vector from the origin of the vector space. But according to Wikipedia, a norm is specified as follows:

*In linear algebra, functional analysis, and related areas of mathematics, a **norm** is a function that satisfies certain properties pertaining to scalability and additivity, and assigns a strictly positive real number to each vector in a vector space over the field of real or complex numbers—except for the zero vector, which is assigned zero.*

**Distance Measures and Norms**

When you do not want to measure the distance between two vectors but rather calculate the norm of one vectors, then you normally just take the origin, e.g. (0,0,0) in a 3-dim space as the second vector.

* **$L^0$ norm**: The $L^0$ norm is the number of non-zero elements in a vector. Then it is not strictly a measure of a distance.
* **Manhattan distance/norm**, also called Taxicab distance (the $L^1$ norm, sometimes written $\ell_1$ norm)
    * The sum of the absolute values of the vector
    * $d_1(p,q) = ||p - q||_1 = \sum_{i=1}^n |p_i - q_i|$ where $(p,q)$ are vectors $p = (p_1, p_2, ..., p_n)$ and $q = (q_1, q_2, ..., q_n)$
* **Euclidean distance/norm** (the $L^2$ norm, sometimes written $\ell_2$ norm)
    * The square root of the sum of the squared vector values
    * Distance: $d(p, q) = \sqrt{\sum_{i=1}^n (q_i - p_i)^2}$
    * Length/norm: $||p|| = \sqrt{p^2_1 + p^2_2 + ... + p^2_n} = \sqrt{p \cdot p}$
* **Chebyshev distance/norm** (the $L^\infty$ norm or max norm, sometimes written $\ell_\infty$ norm)
    * Maximum vector values
* **Cosine similariy**
    * The cosine of the angle between two vectors. Take the dot product of the two vectors and divide by the two lengths.  

If you are curious about what the "L" actually stands for: https://www.quora.com/What-does-the-L-in-L%E2%82%81-norm-or-L%E2%82%82-norm-stand-for 
-> L is for Lebesgue. The Lebesgue space $L^p$ consists of all functions f such that the Lebesgue integral of $|f|^p $ is finite.

## A little primer on Norms

1-norm: $||w||_1 = |w_1| + |w_2| + ... + |w_N|$

2-norm: $(w^2_1 + w^2_2 + ... + w^2_N)^{\frac{1}{2}}$

p-norm: $(w^p_1 + w^p_2 + ... + w^p_N)^{\frac{1}{p}}$

If you are curious about the connection between Norms and Regularisation: https://towardsdatascience.com/intuitions-on-l1-and-l2-regularisation-235f2db4c261#f810

## Vector L0 Norm

In [6]:
from numpy import array
from numpy.linalg import norm
a = array([0, 2, 3])
print(a)
l0 = norm(a, 0)
print(l0)

[0 2 3]
2.0


## Vector L1 Norm (Manhattan)


The notation for the $L^1$ norm of a vector is $||v||_1$.

In [2]:
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l1 = norm(a, 1)
print(l1)

[1 2 3]
6.0


## Vector L2 Norm (Euclidean)

The notation for the $L^2$ norm of a vector is $||v||_2$

In [4]:
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
l2 = norm(a)
print(l2)

[1 2 3]
3.7416573867739413


## Vector Max Norm

The notation for max norm is $||x||_\infty$

In [5]:
from numpy import inf
from numpy import array
from numpy.linalg import norm
a = array([1, 2, 3])
print(a)
maxnorm = norm(a, inf)
print(maxnorm)

[1 2 3]
3.0


## Cosine Similarity

This one is not a norm! This measure is often used in Natural Language Processing for word embeddings to check how similar certain words are. Cosine similarity ignores the magnitude difference of the vectors and only checks in how far two vectors point into the same direction.

In [14]:
import numpy as np
from sklearn.metrics.pairwise import cosine_similarity
 
# vectors
a = np.array([1,2,3])
b = np.array([1,1,4])
 
# manually compute cosine similarity
dot = np.dot(a, b)
norma = np.linalg.norm(a)
normb = np.linalg.norm(b)
cos_man = dot / (norma * normb) # l2 norm

print("Manual computation of cos sim: {}".format(cos_man))

vec1 = np.array([[1,2,3]])
vec2 = np.array([[1,1,4]])
cos_aut = cosine_similarity(vec1, vec2)
print("Automatic computation of cos sim: {}".format(cos_aut))

Manual computation of cos sim: 0.9449111825230682
Automatic computation of cos sim: [[0.94491118]]
